version: '3'
services:
  # docker run -itd -e DERP_HOSTNAME=b2.laisky.com -p 443:443 -p 3478:3478 --name derper ppcelery/derper:20211020-v2
  # docker run -itd -e DERP_HOSTNAME=b2.laisky.com --net host --name derper ppcelery/derper:20211020-v2
  derper:
    image: ppcelery/derper:20221014-v2
    restart: always
    environment:
      ADDR: b1.laisky.com
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    ports:
      - 443:443
      - 3478:3478/udp
    dns:
      - 8.8.8.8
      - 1.1.1.1

  v2ray:
    image: v2ray/official:latest
    restart: always
    network_mode: host
    dns:
      - 8.8.8.8
      - 1.1.1.1
    # ports:
    #   - 1021:1021/udp
    #   - localhost:9953:9953
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    volumes:
      - /opt/configs/v2ray:/etc/v2ray:ro
    command: /usr/bin/v2ray/v2ray -config=/etc/v2ray/config.json

  trojan-go:
    image: ppcelery/trojan-go:20221018
    restart: always
    network_mode: host
    dns:
      - 8.8.8.8
      - 1.1.1.1
    # ports:
    #   - 1021:1021/udp
    #   - localhost:9953:9953
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    volumes:
      - /opt/configs/trojan-go/b1:/etc/torjan-go/config:ro
      - /opt/configs/pki/b1.laisky.com:/etc/torjan-go/pki:ro
    command: /etc/torjan-go/config/server.json

  xray:
    image: teddysun/xray:latest
    restart: always
    network_mode: host
    dns:
      - 8.8.8.8
      - 1.1.1.1
    # ports:
    #   - 1021:1021/udp
    #   - localhost:9953:9953
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    environment:
      - xray.vmess.aead.forced=false
    volumes:
      - /opt/configs/xray:/etc/xray:ro
    # command: /usr/bin/v2ray/v2ray -config=/etc/v2ray/config.json

  glider:
    image: ppcelery/glider:latest
    restart: always
    dns:
      - 8.8.8.8
      - 1.1.1.1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    ports:
      - 100.122.41.16:17777:8080
    volumes:
      - /opt/configs/glider/b1/glider.conf:/app/glider.conf:ro

  dns:
    image: cloudflare/cloudflared
    restart: always
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - 53:53/udp
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    command: proxy-dns --address 0.0.0.0 --port 53
