version: '3'
services:
  derper:
    image: ppcelery/derper:latest
    restart: unless-stopped
    environment:
      ADDR: b1.laisky.com
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - 443:443
      - 3478:3478/udp

  # v2ray:
  #   image: v2ray/official:latest
  #   restart: unless-stopped
  #   network_mode: host
  #   dns:
  #     - 8.8.8.8
  #     - 1.1.1.1
  #   # ports:
  #   #   - 1021:1021/udp
  #   #   - localhost:9953:9953
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #   volumes:
  #     - /opt/configs/v2ray:/etc/v2ray:ro
  #   command: /usr/bin/v2ray/v2ray -config=/etc/v2ray/config.json

  trojan-go:
    image: ppcelery/trojan-go:20230130
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
    # network_mode: host
    ports:
      - 23443:23443
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    volumes:
      - /opt/configs/trojan-go/b1:/etc/torjan-go/config:ro
      - /opt/configs/pki/b1.laisky.com:/etc/torjan-go/pki:ro
    command: /etc/torjan-go/config/server.json

  # xray:
  #   image: teddysun/xray:latest
  #   restart: unless-stopped
  #   network_mode: host
  #   dns:
  #     - 8.8.8.8
  #     - 1.1.1.1
  #   # ports:
  #   #   - 1021:1021/udp
  #   #   - localhost:9953:9953
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #   environment:
  #     - xray.vmess.aead.forced=false
  #   volumes:
  #     - /opt/configs/xray:/etc/xray:ro
  #   # command: /usr/bin/v2ray/v2ray -config=/etc/v2ray/config.json

  glider:
    image: ppcelery/glider:latest
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    # network_mode: host
    ports:
      - "100.122.41.16:17776:17776"
      - "100.122.41.16:17777:17777"
    volumes:
      - /opt/configs/glider/b1/glider.conf:/app/glider.conf:ro

  glider-warp:
    image: ppcelery/glider:latest
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    network_mode: host
    # ports:
    #   - 100.122.41.16:17778:17778
    volumes:
      - /opt/configs/glider/b1/glider-warp.conf:/app/glider.conf:ro

  dns:
    image: cloudflare/cloudflared
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - 53:53/udp
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    command: proxy-dns --address 0.0.0.0 --port 53

  # monitor:
  #   image: prom/node-exporter:latest
  #   container_name: node-exporter
  #   restart: unless-stopped
  #   volumes:
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #     - /:/rootfs:ro
  #   command:
  #     - '--path.procfs=/host/proc'
  #     - '--path.rootfs=/rootfs'
  #     - '--path.sysfs=/host/sys'
  #     - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
  #   ports:
  #     - 100.122.41.16:9100:9100

  mongodb:
    image: mongo:3.6
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "100.122.41.16:27017:27017"
    volumes:
      - /var/lib/mongodb:/data/db
    command: mongod
      --bind_ip 0.0.0.0
      --storageEngine wiredTiger
      --wiredTigerCacheSizeGB 3
      --auth

  doh:
    image: satishweb/doh-server:v2.3.2-ubuntu
    restart: unless-stopped
    # network_mode: host
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - 100.122.41.16:8053:8053
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    environment:
      DEBUG: "0"
      # Upstream DNS server: proto:host:port
      # We are using OpenDNS DNS servers as default,
      # Here is the list of addresses: https://use.opendns.com/
      UPSTREAM_DNS_SERVER: "udp:1.1.1.1:53"
      DOH_HTTP_PREFIX: "/query"
      DOH_SERVER_LISTEN: "0.0.0.0:8053"
      DOH_SERVER_TIMEOUT: "10"
      DOH_SERVER_TRIES: "3"
      DOH_SERVER_VERBOSE: "true"
