version: '3'
services:
  glider-gfw:
    image: ppcelery/glider:latest
    restart: unless-stopped
    dns:
      - 100.122.41.16
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    ports:
      - 28448:28448
      - 28447:28447
    volumes:
      - /opt/configs/glider/bj/glider-gfw.conf:/app/glider.conf:ro

  glider:
    image: ppcelery/glider:latest
    restart: unless-stopped
    # dns:
    #   - 100.122.41.16
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    ports:
      - 100.96.127.120:17777:17777
    volumes:
      - /opt/configs/glider/bj/glider.conf:/app/glider.conf:ro

  glider-cb:
    image: ppcelery/glider:latest
    restart: unless-stopped
    dns:
      - 100.122.41.16
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    ports:
      # - 100.96.127.120:17777:8080
      - 28449:8448
    volumes:
      - /opt/configs/glider/bj/glider-cb.conf:/app/glider.conf:ro

  doh:
    image: satishweb/doh-server:v2.3.2-ubuntu
    restart: unless-stopped
    dns:
      - 100.122.41.16
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    environment:
      DEBUG: "0"
      UPSTREAM_DNS_SERVER: "udp:100.122.41.16:53"
      DOH_HTTP_PREFIX: "/query"
      DOH_SERVER_LISTEN: "0.0.0.0:8053"
      DOH_SERVER_TIMEOUT: "10"
      DOH_SERVER_TRIES: "3"
      DOH_SERVER_VERBOSE: "true"

  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - URL=bj.laisky.com
      - VALIDATION=dns
      - SUBDOMAINS=wildcard
      - DNSPLUGIN=cloudflare
    volumes:
      - /var/www:/var/www
      - /var/log/nginx:/var/log/nginx
      - /opt/configs/swag/bj:/config
      - /opt/configs/nginx/conf.d/bj:/config/nginx/site-confs
    ports:
      - 10443:443
    restart: unless-stopped

  # dns:
  #   image: axeleroy/dnsproxy:latest
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #   environment:
  #     - ARGS=-u 100.122.41.16:53 --cache
  #   ports:
  #     - 100.96.127.120:53:53/udp

  derper:
    image: ppcelery/derper:latest
    restart: unless-stopped
    dns:
      - 100.122.41.16
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    volumes:
      - /opt/configs/swag/bj/etc/letsencrypt/live/bj.laisky.com/fullchain.pem:/etc/live/bj.laisky.com.crt:ro
      - /opt/configs/swag/bj/etc/letsencrypt/live/bj.laisky.com/privkey.pem:/etc/live/bj.laisky.com.key:ro
    ports:
      - 3478:3478/udp
      - 12444:12444
    entrypoint: /app/derper -c=$HOME/derper.conf --hostname=bj.laisky.com -a :12444 -stun -certdir=/etc/live -certmode=manual
    # command: -certdir=/opt/configs/derper/bj -certmode=manual

  monitor:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 100.96.127.120:9100:9100

  ramjet:
    # image: ppcelery/ramjet:b145697
    image: ppcelery/ramjet:latest
    restart: always
    deploy:
      replicas: 1
    ports:
      - 100.96.127.120:22280:37851
    dns:
      - 100.122.41.16
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
    volumes:
      - /opt/configs/ramjet/prd.py:/app/ramjet/settings/prd.py:ro
      # - /home/ubuntu/data/langchain/index:/var/lib/openai/index
      - /home/ubuntu/data/langchain/index-azure:/var/lib/openai/index
    environment:
      - http_proxy=http://100.122.41.16:17777
      - https_proxy=http://100.122.41.16:17777
      - HTTP_PROXY=http://100.122.41.16:17777
      - HTTPS_PROXY=http://100.122.41.16:17777
      - NO_PROXY=localhost,127.0.0.1,100.64.0.0/10,192.168.0.0/16,10.0.0.0/8,127.0.0.0/8,snake-carp.ts.net,basebit.me
    command: python -m ramjet -e keyword --debug
