version: '3'
services:
  v2ray:
    image: v2ray/official:latest
    restart: always
    network_mode: host
    dns:
      - 8.8.8.8
      - 1.1.1.1
    # ports:
    #   - 1021:1021/udp
    #   - localhost:9953:9953
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
    volumes:
      - /opt/configs/v2ray:/etc/v2ray
    command: /usr/bin/v2ray/v2ray -config=/etc/v2ray/config.json

  shadowsocks:
    build:
      context: ./shadowsocks
    restart: always
    # depends_on:
    #   - fluentd
    network_mode: host
    dns:
      - 8.8.8.8
      - 1.1.1.1
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
    volumes:
      - /opt/configs:/opt/configs:ro
    # ports:
    #     - 1022:1022
        # - 17000:17000
        # - 17001:17001
        # - 20706:20706
        # - 17234:17234
        # - 17419:17419
        # - 10310:10310
        # - 18887:18887
        # - 14910:14910
        # - 10019:10019
        # - 16666:16666

  shadowsocks-rss:
    build:
      context: ./shadowsocks-rss
    restart: always
    # depends_on:
    #   - fluentd
    network_mode: host
    dns:
      - 8.8.8.8
      - 1.1.1.1
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
    volumes:
      - /opt/configs:/opt/configs:ro
    # ports:
    #     - 1023:1023
        # - 16667:16667
        # - 18888:18888
        # - 14911:14911
        # - 10020:10020
        # - 17002:17002


  mongodb-auth:
    image: mongo:3.6
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
    network_mode: host
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - /var/lib/mongodb:/data/db
    command: mongod --auth

  go-ramjet:
    image: ppcelery/go-ramjet:e8cd49b
    restart: "always"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    logging:
      driver: "json-file"
      options:
        max-size: 10m
    environment:
      - TASKS=heartbeat,ssl-monitor,keyword
    volumes:
      - /opt/configs/go-ramjet/settings.yml:/etc/go-ramjet/settings/settings.yml
    ports:
      - 127.0.0.1:24456:24456
