version: '3'
services:
  postgre:
    image: ppcelery/postgres:17.11-bookworm
    restart: unless-stopped
    stop_grace_period: 90s
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    env_file:
      - /opt/configs/env/dev/postgre.env
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    ports:
      - 100.75.198.70:5432:5432
