version: '3'
services:
  postgre:
    # image: ppcelery/postgres:latest
    image: ppcelery/postgres:17.6-bookworm
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    env_file:
      - /opt/configs/env/dev/postgre.env
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    ports:
      - 100.75.198.70:5432:5432
