version: '3'
services:
  mongodb:
    image: mongo:3.6
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
    networks:
      - VPC
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - /var/lib/mongodb:/data/db

  fluentd:
    image: ppcelery/fluentd-docker-image
    restart: always
    depends_on:
      - mongodb
    networks:
      - VPC
    dns:
      - 8.8.8.8
      - 1.1.1.1
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
    volumes:
      - /var/log:/var/log
      - /var/lib/fluentd:/fluentd/log
      - /opt/configs/fluent/fluentd.conf:/fluentd/etc/fluent.conf
    links:
      - mongodb:mongodb
    ports:
      - 127.0.0.1:24224:24224

  nginx:
    image: nginx:1.15.0-alpine
    restart: always
    network_mode: host
    dns:
      - 8.8.8.8
      - 1.1.1.1
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
    volumes:
      - /opt/configs/nginx/conf.d:/etc/nginx/conf.d
      - /var/www:/var/www
      - /var/log:/var/log
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/ssl:/etc/ssl
      - /home/laisky/repo/laisky-blog/gargantua:/www/laisky-blog/gargantua

  # v2ray:
  #   image: v2ray/official
  #   restart: always
  #   networks:
  #     - VPC
  #   dns:
  #     - 8.8.8.8
  #     - 1.1.1.1
  #   ports:
  #     - 1021:1021/udp
  #     - 9953:9953
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "30m"
  #   volumes:
  #     - /opt/configs/v2ray/config.json:/etc/v2ray/config.json
  #   command: /usr/bin/v2ray/v2ray -config=/etc/v2ray/config.json

  shadowsocks:
    build:
      context: ./shadowsocks
    restart: always
    depends_on:
      - fluentd
    networks:
      - VPC
    dns:
      - 8.8.8.8
      - 1.1.1.1
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
    volumes:
      - /opt/configs:/opt/configs:ro
    ports:
        - 1022:1022
        - 17000:17000
        - 17001:17001
        - 20706:20706
        - 17234:17234
        - 17419:17419
        - 10310:10310
        - 18887:18887
        - 14910:14910
        - 10019:10019
        - 16666:16666

  shadowsocks-rss:
    build:
      context: ./shadowsocks-rss
    restart: always
    depends_on:
      - fluentd
    networks:
      - VPC
    dns:
      - 8.8.8.8
      - 1.1.1.1
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
    volumes:
      - /opt/configs:/opt/configs:ro
    ports:
        - 1023:1023
        - 16667:16667
        - 18888:18888
        - 14911:14911
        - 10020:10020
        - 17002:17002

  rocketchat:
    image: rocketchat/rocket.chat:0.66.0-rc.0
    restart: always
    depends_on:
      - mongodb
      - fluentd
    networks:
      - VPC
    dns:
      - 8.8.8.8
      - 1.1.1.1
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
    volumes:
      - /var/lib/rocketchat/data/uploads:/app/uploads
    environment:
      - PORT=3000
      - ROOT_URL=https://chat.laisky.com
      - MONGO_URL=mongodb://mongodb:27017/rocketchat
    ports:
      - 127.0.0.1:27300:3000

  # hubot:
  #   image: rocketchat/hubot-rocketchat
  #   restart: always
  #   depends_on:
  #     - rocketchat
  #     - fluentd
  #   networks:
  #     - VPC
  #   dns:
  #     - 8.8.8.8
  #     - 1.1.1.1
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "30m"
  #   environment:
  #     - ROCKETCHAT_ROOM=''
  #     - LISTEN_ON_ALL_PUBLIC=true
  #     - ROCKETCHAT_USER=bot
  #     - ROCKETCHAT_PASSWORD=bot
  #     - ROCKETCHAT_AUTH=password
  #     - ROCKETCHAT_URL=http://rocketchat:3000
  #     - BOT_NAME=bot
  #     - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-diagnostics
  #   links:
  #     - rocketchat:rocketchat
  #   ports:
  #     - 127.0.0.1:27301:3001

  ramjet:
    build:
      context: ./ramjet
    restart: always
    depends_on:
      - mongodb
    networks:
      - VPC
    dns:
      - 8.8.8.8
      - 1.1.1.1
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
    volumes:
      - /opt/configs/ramjet/prd.py:/app/ramjet/settings/prd.py
    ports:
      - 127.0.0.1:37851:37851
    entrypoint: python -m ramjet -e keyword

  # gargantua:
  #   build:
  #     context: ./gargantua
  #   restart: always
  #   depends_on:
  #     - mongodb
  #   networks:
  #     - VPC
  #   dns:
  #     - 8.8.8.8
  #     - 1.1.1.1
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "30m"
  #   environment:
  #     DBHOST: mongodb
  #     DBPORT: 27017
  #   volumes:
  #     - /opt/configs/laisky-blog:/laisky-blog/settings:ro
  #   ports:
  #     - 127.0.0.1:27850:27850
  #   command: run_gargantua

networks:
  VPC:
    driver: bridge

