version: '3'
services:
  derper:
    image: ppcelery/derper:latest
    restart: unless-stopped
    environment:
      ADDR: hk.laisky.com
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - /opt/configs/swag/hk/etc/letsencrypt/live/hk.laisky.com/fullchain.pem:/etc/live/hk.laisky.com.crt:ro
      - /opt/configs/swag/hk/etc/letsencrypt/live/hk.laisky.com/privkey.pem:/etc/live/hk.laisky.com.key:ro
    ports:
      - 3478:3478/udp
      - 12444:12444
    entrypoint: /app/derper -c=$HOME/derper.conf --hostname=hk.laisky.com -a :12444 -stun -certdir=/etc/live -certmode=manual

  xray:
    image: teddysun/xray:latest
    restart: unless-stopped
    # network_mode: host
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - 24809:24809
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    environment:
      - xray.vmess.aead.forced=false
    volumes:
      - /opt/configs/xray:/etc/xray:ro

  trojan-go:
    image: ppcelery/trojan-go:latest
    restart: unless-stopped
    # network_mode: host
    dns:
      - 8.8.8.8
      - 1.1.1.1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    ports:
      - 23443:23443
    volumes:
      - /opt/configs/swag/hk/etc/letsencrypt/live/hk.laisky.com/fullchain.pem:/etc/live/hk.laisky.com.crt:ro
      - /opt/configs/swag/hk/etc/letsencrypt/live/hk.laisky.com/privkey.pem:/etc/live/hk.laisky.com.key:ro
      - /opt/configs/trojan-go/hk:/etc/torjan-go/config:ro
    command: /etc/torjan-go/config/server.json

  glider:
    image: ppcelery/glider:latest
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    network_mode: host
    # ports:
    #   - 100.92.2.80:17777:17777
    volumes:
      - /opt/configs/glider/hk/glider.conf:/app/glider.conf:ro

  glider-isp:
    image: ppcelery/glider:latest
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    # network_mode: host
    ports:
      - "100.97.189.32:17780:17777"
    volumes:
      - /opt/configs/glider/hk/glider-isp.conf:/app/glider.conf:ro

  glider-sg:
    image: ppcelery/glider:latest
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    # network_mode: host
    ports:
      - "100.97.189.32:17780:17777"
    volumes:
      - /opt/configs/glider/hk/glider-sg.conf:/app/glider.conf:ro

  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - URL=hk.laisky.com
      - VALIDATION=dns
      - SUBDOMAINS=wildcard
      - DNSPLUGIN=cloudflare
    volumes:
      # - /var/log/nginx:/var/log/nginx
      - /opt/configs/swag/hk:/config
      # - /opt/configs/nginx/conf.d/b1:/config/nginx/site-confs
    dns:
      - 8.8.8.8
      - 1.1.1.1
    # ports:
    #   - 443:443
    #   - 80:80
    restart: unless-stopped

  hysteria:
    image: tobyxdd/hysteria
    restart: "always"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    ports:
      - 28998:8998/udp
    volumes:
      - /opt/configs/swag/hk/etc/letsencrypt:/etc/letsencrypt:ro
      - /opt/configs/hysteria/hk/server.yaml:/etc/hysteria/server.yaml:ro
    command: ["server", "-c", "/etc/hysteria/server.yaml"]

  nginx:
    image: nginx:1.25
    restart: unless-stopped
    # network_mode: host
    ports:
      # - 100.122.41.16:443:443
      - 443:443
      # - 80:80
    dns:
      - 8.8.8.8
      - 1.1.1.1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    volumes:
      - /var/www:/var/www
      - /var/log:/var/log
      - /var/lib/nginx/cache/s3:/var/lib/nginx/cache/s3
      - /opt/configs/nginx/conf.d/hk:/etc/nginx/conf.d:ro
      - /opt/configs/nginx:/opt/configs/nginx:ro
