version: '3'
services:
  derper:
    image: ppcelery/derper:20221120
    restart: always
    environment:
      ADDR: hk.laisky.com
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    ports:
      - 443:443
      - 3478:3478/udp
    dns:
      - 8.8.8.8
      - 1.1.1.1

  # mongodb:
  #   image: mongo:6.0.1
  #   restart: always
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #   ports:
  #     - "100.92.2.80:27017:27017"
  #   dns:
  #     - 8.8.8.8
  #     - 1.1.1.1
  #   volumes:
  #     - /var/lib/mongodb:/data/db
  #   command: mongod
  #     --bind_ip 0.0.0.0
  #     --storageEngine wiredTiger
  #     --wiredTigerCacheSizeGB 3
  #     # --auth

  v2ray:
    image: v2ray/official:latest
    restart: always
    network_mode: host
    dns:
      - 8.8.8.8
      - 1.1.1.1
    # ports:
    #   - 1021:1021/udp
    #   - localhost:9953:9953
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    volumes:
      - /opt/configs/v2ray:/etc/v2ray:ro
    command: /usr/bin/v2ray/v2ray -config=/etc/v2ray/config.json

  xray:
    image: teddysun/xray:latest
    restart: always
    # network_mode: host
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - 24809:24809
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    environment:
      - xray.vmess.aead.forced=false
    volumes:
      - /opt/configs/xray:/etc/xray:ro

  trojan-go:
    image: ppcelery/trojan-go:20221018
    restart: always
    network_mode: host
    dns:
      - 8.8.8.8
      - 1.1.1.1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    volumes:
      - /opt/configs/trojan-go/hk:/etc/torjan-go/config:ro
      - /opt/configs/pki/hk.laisky.com:/etc/torjan-go/pki:ro
    command: /etc/torjan-go/config/server.json

  dns:
    image: cloudflare/cloudflared
    restart: always
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - 53:53/udp
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    command: proxy-dns --address 0.0.0.0 --port 53

  monitor:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 100.92.2.80:9100:9100
