version: '3'
services:
  # mongodb:
  #   image: mongo:3.6
  #   restart: always
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "30m"
  #   networks:
  #     - VPC
  #   dns:
  #     - 8.8.8.8
  #     - 1.1.1.1
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - /var/lib/mongodb:/data/db
  #   command: mongod --auth

  # fluentd:
  #   image: ppcelery/fluentd-docker-image
  #   restart: always
  #   depends_on:
  #     - mongodb
  #   networks:
  #     - VPC
  #   dns:
  #     - 8.8.8.8
  #     - 1.1.1.1
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "30m"
  #   volumes:
  #     - /var/log:/var/log
  #     - /var/lib/fluentd:/fluentd/log
  #     - /opt/configs/fluent/fluentd.conf:/fluentd/etc/fluent.conf
  #   links:
  #     - mongodb:mongodb
  #   ports:
  #     - 127.0.0.1:24224:24224

  nginx:
    image: nginx:1.15.6-alpine
    restart: always
    network_mode: host
    dns:
      - 8.8.8.8
      - 1.1.1.1
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
    volumes:
      - /opt/configs/nginx/conf.d:/etc/nginx/conf.d
      - /var/www:/var/www
      - /var/log:/var/log
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/ssl:/etc/ssl
      - /home/laisky/repo/laisky-blog/gargantua:/www/laisky-blog/gargantua

  graphql:
    image: ppcelery/laisky-blog-graphql:13d51ae
    restart: always
    networks:
      - VPC
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - 127.0.0.1:17800:8080
    volumes:
      - /opt/configs/laisky-blog-graphql:/etc/laisky-blog-graphql
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
    command: ./go-graphql-srv --addr=0.0.0.0:8080 --config=/etc/laisky-blog-graphql -t telegram

  ramjet:
    image: ppcelery/ramjet:e8cd49b
    # build:
    #   context: ./ramjet
    restart: always
    # depends_on:
    #   - mongodb
    networks:
      - VPC
    dns:
      - 8.8.8.8
      - 1.1.1.1
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
    volumes:
      - /opt/configs/ramjet/prd.py:/app/ramjet/settings/prd.py
    ports:
      - 127.0.0.1:37851:37851
    entrypoint: python -m ramjet -e keyword

  # gargantua:
  #   build:
  #     context: ./gargantua
  #   restart: always
  #   depends_on:
  #     - mongodb
  #   networks:
  #     - VPC
  #   dns:
  #     - 8.8.8.8
  #     - 1.1.1.1
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "30m"
  #   environment:
  #     DBHOST: mongodb
  #     DBPORT: 27017
  #   volumes:
  #     - /opt/configs/laisky-blog:/laisky-blog/settings:ro
  #   ports:
  #     - 127.0.0.1:27850:27850
  #   command: run_gargantua

  go-ramjet:
    image: ppcelery/go-ramjet:f090a42
    restart: "always"
    # depends_on:
    #   - mongodb
    networks:
      - VPC
    dns:
      - 8.8.8.8
      - 1.1.1.1
    logging:
      driver: "json-file"
      options:
        max-size: 10m
    environment:
      - TASKS=heartbeat,ssl-monitor
    volumes:
      - /opt/configs/go-ramjet/settings.yml:/etc/go-ramjet/settings/settings.yml
    ports:
      - 127.0.0.1:24456:24456

  # # dns over https
  # cloudflared:
  #   image: ppcelery/cloudflared
  #   restart: "always"
  #   # build:
  #   #   context: ./cloudflared
  #   network_mode: host  # port 53, only host mode support udp
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: 10m
  #   environment:
  #     - DNS1=1.1.1.1
  #     - DNS2=1.0.0.1


networks:
  VPC:
    driver: bridge

