version: '3'
services:
  mongodb:
    image: mongo:3.6
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
    network_mode: host
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - /var/lib/mongodb:/data/db
    command: mongod --auth --bind_ip 0.0.0.0 --storageEngine wiredTiger

  # fluentd:
  #   image: ppcelery/fluentd-docker-image
  #   restart: always
  #   depends_on:
  #     - mongodb
  #   networks:
  #     - VPC
  #   dns:
  #     - 8.8.8.8
  #     - 1.1.1.1
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "30m"
  #   volumes:
  #     - /var/log:/var/log
  #     - /var/lib/fluentd:/fluentd/log
  #     - /opt/configs/fluent/fluentd.conf:/fluentd/etc/fluent.conf
  #   links:
  #     - mongodb:mongodb
  #   ports:
  #     - 127.0.0.1:24224:24224

  v2ray:
    image: v2ray/official:latest
    restart: always
    network_mode: host
    dns:
      - 8.8.8.8
      - 1.1.1.1
    # ports:
    #   - 1021:1021/udp
    #   - localhost:9953:9953
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
    volumes:
      - /opt/configs/v2ray:/etc/v2ray:ro
    command: /usr/bin/v2ray/v2ray -config=/etc/v2ray/config.json

  nginx:
    image: nginx:1.15.6-alpine
    restart: always
    network_mode: host
    dns:
      - 8.8.8.8
      - 1.1.1.1
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
    volumes:
      - /var/www:/var/www
      - /var/log:/var/log
      - /opt/configs/nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/ssl:/etc/ssl:ro
      - /home/laisky/repo/laisky-blog/gargantua:/www/laisky-blog/gargantua:ro

  graphql:
    image: ppcelery/laisky-blog-graphql:cc956ba
    restart: always
    depends_on:
      - mongodb
    networks:
      - VPC
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - 127.0.0.1:17800:8080
    volumes:
      - /opt/configs/laisky-blog-graphql:/etc/laisky-blog-graphql:ro
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: "/etc/laisky-blog-graphql/gcp-general-sa.json"
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
    command: ./go-graphql-srv --addr=0.0.0.0:8080 --config=/etc/laisky-blog-graphql -t telegram

  ramjet:
    image: ppcelery/ramjet:db0af49
    # build:
    #   context: ./ramjet
    restart: always
    depends_on:
      - mongodb
    networks:
      - VPC
    dns:
      - 8.8.8.8
      - 1.1.1.1
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
    volumes:
      - /opt/configs/ramjet/prd.py:/app/ramjet/settings/prd.py:ro
    ports:
      - 127.0.0.1:37851:37851
    entrypoint: python -m ramjet -e keyword

  # gargantua:
  #   build:
  #     context: ./gargantua
  #   restart: always
  #   depends_on:
  #     - mongodb
  #   networks:
  #     - VPC
  #   dns:
  #     - 8.8.8.8
  #     - 1.1.1.1
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "30m"
  #   environment:
  #     DBHOST: mongodb
  #     DBPORT: 27017
  #   volumes:
  #     - /opt/configs/laisky-blog:/laisky-blog/settings:ro
  #   ports:
  #     - 127.0.0.1:27850:27850
  #   command: run_gargantua

  go-ramjet:
    image: ppcelery/go-ramjet:78caf6f
    restart: "always"
    depends_on:
      - mongodb
    networks:
      - VPC
    dns:
      - 8.8.8.8
      - 1.1.1.1
    logging:
      driver: "json-file"
      options:
        max-size: 10m
    environment:
      - TASKS=heartbeat,ssl-monitor,rss,keyword
    volumes:
      - /opt/configs/go-ramjet/settings.yml:/etc/go-ramjet/settings/settings.yml:ro
      - /var/www/public:/Users/laisky/Downloads/
    ports:
      - 127.0.0.1:24456:24456

  # # dns over https
  # cloudflared:
  #   image: ppcelery/cloudflared
  #   restart: "always"
  #   # build:
  #   #   context: ./cloudflared
  #   network_mode: host  # port 53, only host mode support udp
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: 10m
  #   environment:
  #     - DNS1=1.1.1.1
  #     - DNS2=1.0.0.1


networks:
  VPC:
    driver: bridge
