version: '3'
services:
  # db ./derper -t ppcelery/derper:20220920
  derper:
    image: ppcelery/derper:20221014-v5
    restart: always
    environment:
      ADDR: derper.tk.laisky.com
      PORT: 10444
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    ports:
      # - 127.0.0.1:10444:10444
      - 3478:3478/udp
    dns:
      - 8.8.8.8
      - 1.1.1.1

  # mongodb:
  #   image: mongo:3.6
  #   restart: always
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #   network_mode: host
  #   dns:
  #     - 8.8.8.8
  #     - 1.1.1.1
  #   volumes:
  #     - /var/lib/mongodb:/data/db
  #   command: mongod --bind_ip 0.0.0.0 --storageEngine wiredTiger --auth

  # curl -kv https://pccs.laisky.com/sgx/certification/v3/rootcacrl
  # pccs:
  #   image: ppcelery/pccs:v2.2
  #   # build:
  #   #   context: ./pccs
  #   restart: always
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #   ports:
  #     - 127.0.0.1:8081:8081
  #   dns:
  #     - 8.8.8.8
  #     - 1.1.1.1
  #   volumes:
  #     - /opt/configs/intel/pccs/default.json:/opt/intel/pccs/config/default.json:ro
  #     - /opt/configs/intel/pccs/ssl_key:/opt/intel/pccs/ssl_key

  # codeserver:
  #   image: codercom/code-server:latest
  #   restart: always
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #   ports:
  #     - 38080:8080
  #   dns:
  #     - 8.8.8.8
  #     - 1.1.1.1
  #   volumes:
  #     - /home/laisky/repo/code-server:/home/coder/project
  #     - /opt/configs/codeserver:/home/coder/.config/code-server

  # fluentd:
  #   image: ppcelery/fluentd-docker-image
  #   restart: always
  #   depends_on:
  #     - mongodb
  #   networks:
  #     - VPC
  #   dns:
  #     - 8.8.8.8
  #     - 1.1.1.1
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #   volumes:
  #     - /var/log:/var/log
  #     - /var/lib/fluentd:/fluentd/log
  #     - /opt/configs/fluent/fluentd.conf:/fluentd/etc/fluent.conf
  #   links:
  #     - mongodb:mongodb
  #   ports:
  #     - 127.0.0.1:24224:24224

  v2ray:
    image: v2ray/official:latest
    restart: always
    network_mode: host
    dns:
      - 8.8.8.8
      - 1.1.1.1
    # ports:
    #   - 1021:1021/udp
    #   - localhost:9953:9953
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    volumes:
      - /opt/configs/v2ray:/etc/v2ray:ro
    command: /usr/bin/v2ray/v2ray -config=/etc/v2ray/config.json

  trojan-go:
    image: p4gefau1t/trojan-go:latest
    restart: always
    network_mode: host
    dns:
      - 8.8.8.8
      - 1.1.1.1
    # ports:
    #   - 1021:1021/udp
    #   - localhost:9953:9953
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    volumes:
      - /opt/configs/trojan-go/tk:/etc/torjan-go/config:ro
      - /opt/configs/pki/tk.laisky.com:/etc/torjan-go/pki:ro
    command: /etc/torjan-go/config/server.json

  xray:
    image: teddysun/xray:latest
    restart: always
    network_mode: host
    dns:
      - 8.8.8.8
      - 1.1.1.1
    # ports:
    #   - 1021:1021/udp
    #   - localhost:9953:9953
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    environment:
      - xray.vmess.aead.forced=false
    volumes:
      - /opt/configs/xray:/etc/xray:ro
    # command: /usr/bin/v2ray/v2ray -config=/etc/v2ray/config.json

  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    # network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - URL=tk.laisky.com
      - VALIDATION=http
      - SUBDOMAINS=www,dns,derper,* #optional
      # - CERTPROVIDER= #optional
      # - DNSPLUGIN=cloudflare #optional
      # - PROPAGATION= #optional
      # - EMAIL= #optional
      # - ONLY_SUBDOMAINS=false #optional
      # - EXTRA_DOMAINS= #optional
      # - STAGING=false #optional
    volumes:
      - /var/www:/var/www
      - /var/log/nginx:/var/log/nginx
      - /opt/configs/swag/tk:/config
      - /opt/configs/nginx/conf.d/tk:/config/nginx/site-confs
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped

  doh:
    image: satishweb/doh-server:v2.3.2-ubuntu
    restart: always
    # network_mode: host
    dns:
      - 8.8.8.8
      - 1.1.1.1
    # ports:
    #   - 1021:1021/udp
    #   - localhost:9953:9953
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    environment:
      DEBUG: "0"
      # Upstream DNS server: proto:host:port
      # We are using OpenDNS DNS servers as default,
      # Here is the list of addresses: https://use.opendns.com/
      UPSTREAM_DNS_SERVER: "udp:1.1.1.1:53"
      DOH_HTTP_PREFIX: "/query"
      DOH_SERVER_LISTEN: "0.0.0.0:8053"
      DOH_SERVER_TIMEOUT: "10"
      DOH_SERVER_TRIES: "3"
      DOH_SERVER_VERBOSE: "true"
    # ports:
    #   - 127.0.0.1:8053:8053

  # nginx:
  #   image: nginx:1.21.3-alpine
  #   restart: always
  #   # network_mode: host
  #   ports:
  #     - 444:443
  #     - 80:80
  #   dns:
  #     - 8.8.8.8
  #     - 1.1.1.1
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #   volumes:
  #     - /var/www:/var/www
  #     - /var/log/nginx:/var/log/nginx
  #     - /opt/configs/nginx/conf.d/tk:/etc/nginx/conf.d:ro
  #     - /opt/configs/pki/tk.laisky.com:/opt/configs/pki/tk.laisky.com:ro

  # graphql:
  #   # image: ppcelery/laisky-blog-graphql:a689e1f
  #   image: ppcelery/laisky-blog-graphql:7986be7
  #   restart: always
  #   # depends_on:
  #   #   - mongodb
  #   # networks:
  #   #   - VPC
  #   dns:
  #     - 8.8.8.8
  #     - 1.1.1.1
  #   ports:
  #     - 127.0.0.1:17800:8080
  #   volumes:
  #     - /opt/configs/laisky-blog-graphql:/etc/laisky-blog-graphql:ro
  #   environment:
  #     GOOGLE_APPLICATION_CREDENTIALS: "/etc/laisky-blog-graphql/gcp-general-sa.json"
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #   command: api --listen=0.0.0.0:8080
  #     --config=/etc/laisky-blog-graphql/settings.yml
  #     --log-level=debug
  #     -t telegram

  # ramjet:
  #   # image: ppcelery/ramjet:4a9bdc6
  #   image: ppcelery/ramjet:48735a7
  #   # build:
  #   #   context: ./ramjet
  #   restart: always
  #   # depends_on:
  #   #   - mongodb
  #   # networks:
  #   #   - VPC
  #   dns:
  #     - 8.8.8.8
  #     - 1.1.1.1
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #   volumes:
  #     - /opt/configs/ramjet/prd.py:/app/ramjet/settings/prd.py:ro
  #     # - /var/www/uploads/twitter:/var/www/uploads/twitter
  #   ports:
  #     - 127.0.0.1:37851:37851
  #   entrypoint: python -m ramjet -e keyword

  # gargantua:
  #   build:
  #     context: ./gargantua
  #   restart: always
  #   depends_on:
  #     - mongodb
  #   networks:
  #     - VPC
  #   dns:
  #     - 8.8.8.8
  #     - 1.1.1.1
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #   environment:
  #     DBHOST: mongodb
  #     DBPORT: 27017
  #   volumes:
  #     - /opt/configs/laisky-blog:/laisky-blog/settings:ro
  #   ports:
  #     - 127.0.0.1:27850:27850
  #   command: run_gargantua

  # go-ramjet:
  #   image: ppcelery/go-ramjet:78caf6f
  #   restart: "always"
  #   depends_on:
  #     - mongodb
  #   networks:
  #     - VPC
  #   dns:
  #     - 8.8.8.8
  #     - 1.1.1.1
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #   environment:
  #     - TASKS=heartbeat,ssl-monitor,rss,keyword
  #   volumes:
  #     - /opt/configs/go-ramjet/settings.yml:/etc/go-ramjet/settings/settings.yml:ro
  #     - /var/www/public:/Users/laisky/Downloads/
  #   ports:
  #     - 127.0.0.1:24456:24456

  # # dns over https
  # cloudflared:
  #   image: ppcelery/cloudflared
  #   restart: "always"
  #   # build:
  #   #   context: ./cloudflared
  #   network_mode: host  # port 53, only host mode support udp
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #   environment:
  #     - DNS1=1.1.1.1
  #     - DNS2=1.0.0.1

# go-fluentd:
#     image: ppcelery/go-fluentd:1.12.7
#     restart: "on-failure"
#     networks:
#       - VPC
#     dns:

#       - 8.8.8.8
#       - 1.1.1.1
#     ports:
#       - 127.0.0.1:22280:22280
#       - 127.0.0.1:24225:24225
#     mem_limit: 1g
#     logging:
#       driver: "json-file"
#       options:
#         max-size: "10m"
#     volumes:
#       - /opt/configs/go-fluentd:/etc/go-fluentd
#       - /var/log/go-concator:/data/log/fluentd/go-concator
#     command:
#       ./go-fluentd
#         --config=/etc/go-fluentd/settings-prd.yml
#         --env=prod
#         --addr=0.0.0.0:22800
#         --log-level=error
#         --log-alert
#         --host=linode
#         --enable-auto-gc

  # wireguard:
  #   image: linuxserver/wireguard
  #   network_mode: host
  #   # ports:
  #   #   - 51820:51820/udp
  #   cap_add:
  #     - NET_ADMIN
  #     - SYS_MODULE
  #   volumes:
  #     - /lib/modules:/lib/modules
  #     - /opt/configs/wireguard/linode/wg0.conf:/config/wg0.conf:ro
  #     - /opt/configs/wireguard/peers.conf:/config/peers.conf:ro

# networks:
#   VPC:
#     driver: bridge
