version: '3'
services:
  derper:
    image: ppcelery/derper:latest
    restart: unless-stopped
    environment:
      ADDR: vultr.laisky.com
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - /opt/configs/swag/vultr/etc/letsencrypt/live/vultr.laisky.com/fullchain.pem:/etc/live/vultr.laisky.com.crt:ro
      - /opt/configs/swag/vultr/etc/letsencrypt/live/vultr.laisky.com/privkey.pem:/etc/live/vultr.laisky.com.key:ro
    ports:
      - 3478:3478/udp
      - 12444:12444
    entrypoint: /app/derper -c=$HOME/derper.conf --hostname=vultr.laisky.com -a :12444 -stun -certdir=/etc/live -certmode=manual

  glider:
    image: ppcelery/glider:latest
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    # network_mode: host
    ports:
      - 100.71.231.111:17777:17777
    volumes:
      - /opt/configs/glider/vultr/glider.conf:/app/glider.conf:ro

  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - URL=vultr.laisky.com
      - VALIDATION=dns
      - SUBDOMAINS=wildcard
      - DNSPLUGIN=cloudflare
    volumes:
      # - /var/log/nginx:/var/log/nginx
      - /opt/configs/swag/vultr:/config
      # - /opt/configs/nginx/conf.d/b1:/config/nginx/site-confs
    dns:
      - 8.8.8.8
      - 1.1.1.1
    # ports:
    #   - 443:443
    #   - 80:80
    restart: unless-stopped

  hysteria:
    image: tobyxdd/hysteria
    restart: "always"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    ports:
      - 28998:8998/udp
    volumes:
      - /opt/configs/swag/vultr/etc/letsencrypt:/etc/letsencrypt:ro
      - /opt/configs/hysteria/vultr/server.yaml:/etc/hysteria/server.yaml:ro
    command: ["server", "-c", "/etc/hysteria/server.yaml"]

  haproxy:
    image: haproxy:2.5.1-alpine
    restart: always
    dns:
      - 8.8.8.8
      - 1.1.1.1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    network_mode: host
    volumes:
      - /opt/configs/haproxy/vultr.cfg:/etc/haproxy/proxy.cfg:ro
    command: -f /etc/haproxy/proxy.cfg
