version: '3'
services:
  derper:
    image: ppcelery/derper:latest
    restart: unless-stopped
    environment:
      ADDR: vultr.laisky.com
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    ports:
      - 443:443
      - 3478:3478/udp
    dns:
      - 8.8.8.8
      - 1.1.1.1

  glider:
    image: ppcelery/glider:latest
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    # network_mode: host
    ports:
      - 100.71.231.111:17777:17777
    volumes:
      - /opt/configs/glider/vultr/glider.conf:/app/glider.conf:ro

  # haproxy:
  #   image: haproxy:2.5.1-alpine
  #   restart: always
  #   dns:
  #     - 8.8.8.8
  #     - 1.1.1.1
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #   network_mode: host
  #   volumes:
  #     - /opt/configs/haproxy/vultr.cfg:/etc/haproxy/vultr.cfg:ro
  #   command: -f /etc/haproxy/vultr.cfg

  dns:
    image: cloudflare/cloudflared
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - 53:53/udp
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    command: proxy-dns --address 0.0.0.0 --port 53
