version: '3'
services:
  derper:
    image: ppcelery/derper:latest
    restart: unless-stopped
    environment:
      ADDR: vultr.laisky.com
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    ports:
      - 443:443
      - 3478:3478/udp
    dns:
      - 8.8.8.8
      - 1.1.1.1

  glider:
    image: ppcelery/glider:latest
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    # network_mode: host
    ports:
      - 100.71.231.111:17777:17777
    volumes:
      - /opt/configs/glider/vultr/glider.conf:/app/glider.conf:ro

  # dns:
  #   image: axeleroy/dnsproxy:latest
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #   environment:
  #     - ARGS=-u 8.8.8.8:53 -u 1.1.1.1:53 --cache
  #   ports:
  #     - 100.71.231.111:53:53/udp

  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - URL=vultr.laisky.com
      - VALIDATION=dns
      - SUBDOMAINS=wildcard
      - DNSPLUGIN=cloudflare
    volumes:
      # - /var/log/nginx:/var/log/nginx
      - /opt/configs/swag/vultr:/config
      # - /opt/configs/nginx/conf.d/b1:/config/nginx/site-confs
    dns:
      - 8.8.8.8
      - 1.1.1.1
    # ports:
    #   - 443:443
    #   - 80:80
    restart: unless-stopped

  hysteria:
    image: tobyxdd/hysteria
    restart: "always"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    ports:
      - 28998:8998/udp
    volumes:
      - /opt/configs/swag/vultr/etc/letsencrypt:/etc/letsencrypt:ro
      - /opt/configs/hysteria/vultr/server.yaml:/etc/hysteria/server.yaml:ro
    command: ["server", "-c", "/etc/hysteria/server.yaml"]

  go-ramjet:
    # image: ppcelery/go-ramjet:c23124a
    image: ppcelery/go-ramjet:latest
    restart: "always"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    environment:
      - TASKS=heartbeat,gptchat
    volumes:
      - /opt/configs/go-ramjet/settings.yml:/etc/go-ramjet/settings.yml:ro
    dns:
      - 1.1.1.1
      - 8.8.8.8
    ports:
      - 100.71.231.111:24456:24456
    command: -t heartbeat,gptchat -c /etc/go-ramjet/settings.yml --debug

  nginx:
    image: nginx:1.25
    restart: unless-stopped
    network_mode: host
    # ports:
    #   # - 100.122.41.16:443:443
    #   - 443:443
    #   # - 80:80
    dns:
      - 8.8.8.8
      - 1.1.1.1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    volumes:
      - /var/www:/var/www
      - /var/log:/var/log
      - /var/lib/nginx/cache/s3:/var/lib/nginx/cache/s3
      - /opt/configs/nginx/conf.d/b1:/etc/nginx/conf.d:ro
      - /opt/configs/nginx:/opt/configs/nginx:ro
