version: '3'
services:
  derper:
    image: ppcelery/derper:20230320
    restart: unless-stopped
    environment:
      ADDR: vultr.laisky.com
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    ports:
      - 443:443
      - 3478:3478/udp
    dns:
      - 8.8.8.8
      - 1.1.1.1

  glider:
    image: ppcelery/glider:20230115
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    # network_mode: host
    ports:
      - 100.116.159.92:17777:8080
    volumes:
      - /opt/configs/glider/vultr/glider.conf:/app/glider.conf:ro
