apiVersion: 1
datasources:
  - name: Metrics
    uid: obs-metrics
    type: prometheus
    access: proxy
    url: http://victoria-metrics:8428
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: 15s
  - name: Traces
    uid: obs-traces
    type: jaeger
    access: proxy
    url: http://victoria-traces:10428/select/jaeger
    editable: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: obs-logs
        spanStartTimeShift: '-1m'
        spanEndTimeShift: '1m'
        customQuery: true
        query: 'trace_id:="$${__trace.traceId}"'
  - name: Logs
    uid: obs-logs
    type: victoriametrics-logs-datasource
    access: proxy
    url: http://victoria-logs:9428
    editable: false
    jsonData:
      maxLines: 1000
      otelPreset:
        enabled: true
        tracesDatasourceUid: obs-traces
        detection:
          traceIdField: trace_id
          severity:
            field: severity_text
            valueCase: string
            source: manual
